name: maze
description: A pure Dart library for loading and managing tile-based mazes.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.10.1

dependencies:
  csv: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
